In [1]:
import glob
import re
import numpy as np

In [2]:
fcf = glob.glob('./*.txt')

In [3]:
f = open('01.txt','r')
text1 = f.read()

In [4]:
f = open('feature.txt','r')
features = f.read()

In [5]:
feature_list = re.split(r'[` \n]', features)
print(feature_list)

['car', 'passenger', 'seat', 'drive', 'power', 'highway', 'purchase', 'hotel', 'room', 'night', 'staff', 'water', 'location']


In [6]:
Xtrain = []

In [7]:
file_features = []
for feature in feature_list:
    occurance = 0
    for word in re.split(r'[` \-=~!@#$%^&*()_+\[\]{};\'\\:"|<,./<>?]', text1):
        if word == feature: occurance += 1
    file_features.append(occurance)

Xtrain.append(file_features)

In [8]:
print(Xtrain)
print(feature_list)

[[1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]]
['car', 'passenger', 'seat', 'drive', 'power', 'highway', 'purchase', 'hotel', 'room', 'night', 'staff', 'water', 'location']


In [9]:
Xtrain = []

In [10]:
for file_number in range(1, 41):
    
    file_name = "{:02d}.txt".format(file_number)
    f = open(file_name,'r')
    text = f.read()
    
    file_features = []
    for feature in feature_list:
        occurance = 0
        for word in re.split(r'[` \-=~!@#$%^&*()_+\[\]{};\'\\:"|<,./<>?]', text):
            if word == feature: occurance += 1 
        file_features.append(occurance)
        
    Xtrain.append(file_features)

In [11]:
Xtrain = np.asarray(Xtrain)
Xtrain.shape

(40, 13)

In [12]:
Xtest = []

In [13]:
for file_number in range(41, 51):
    
    file_name = "{:02d}.txt".format(file_number)
    f = open(file_name,'r')
    text = f.read()
    
    file_features = []
    for feature in feature_list:
        occurance = 0
        for word in re.split(r'[` \-=~!@#$%^&*()_+\[\]{};\'\\:"|<,./<>?]', text):
            if word == feature: occurance += 1 
        file_features.append(occurance)
        
    Xtest.append(file_features)

In [14]:
Xtest = np.asarray(Xtest)
Xtest.shape

(10, 13)

In [15]:
Y = np.append( np.zeros((1, 20)), np.ones((1, 20)))
Y = Y.reshape(40,1)

Y = np.concatenate((Y,Xtrain), axis=1)

In [16]:
Y.shape, Xtrain.shape

((40, 14), (40, 13))

## Q4

In [17]:
Xtrain = np.concatenate((Xtrain[:20], -Xtrain[20:]))

In [18]:
Y = np.append( np.ones((1, 20)), -np.ones((1, 20)))
Y = Y.reshape(40,1)


Y = np.concatenate((Y,Xtrain), axis=1)

In [19]:
Y.shape

(40, 14)

#### Using Perceptron

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors

In [21]:
a=np.zeros((Y.shape[1],1))

In [22]:
# no. of misclassified samples
sum_wrong=1

#Perceptron
a_iter=a
k=0

while sum_wrong>0 and k<1000:
    
    wrong=np.dot(Y,a_iter)<=0
    sum_wrong=sum(wrong)
    print("sum wrong",sum_wrong)
    sum1=sum(wrong*np.ones((1,Y.shape[1]))*Y)    
    a_iter=a_iter+sum1.reshape(Y.shape[1],1)
    
    k=k+1

print("Final a = {} after k={} iterations".format(np.transpose(a_iter), k, ))

sum wrong [40]
sum wrong [1]
sum wrong [0]
Final a = [[  1.  37.   2.   5.   8.   6.   5.   3. -33. -30.  -5.  -9.  -1. -15.]] after k=3 iterations


In [23]:
#classifier

a_con=a_iter
x=np.arange(0,100,15)

y = -(a_con[0]+sum(a_con[1:-1]*x))/a_con[-1]

y

array([  6.66666667e-02,  -1.19333333e+01,  -2.39333333e+01,
        -3.59333333e+01,  -4.79333333e+01,  -5.99333333e+01,
        -7.19333333e+01])

In [24]:
Xtest.shape

Xtest_temp = np.concatenate((np.ones((10, 1)),Xtest), axis=1)

In [25]:
a_con=a_iter


ans = np.dot(np.transpose(a_con), np.transpose(Xtest_temp))
ans.shape, Xtest.shape

ans

array([[ 128.,  -75., -140.,  266.,  -16.,   75., -116., -164.,   43.,
         -83.]])

#### Using SVM

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors
from cvxopt import solvers
from cvxopt import matrix

In [27]:
Xtrain.shape

(40, 13)

In [28]:
A=matrix(Y,tc='d')
A

<40x14 matrix, tc='d'>

In [29]:
b=matrix(-1*np.ones((A.size[0],1)),tc='d')
b

<40x1 matrix, tc='d'>

In [30]:
q1=np.zeros((1,A.size[1]))
q1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.]])

In [31]:
Q2=np.concatenate((np.zeros((Xtrain.shape[1],1)), np.eye(Xtrain.shape[1])),axis=1)
# Q2

In [32]:
Q=np.concatenate((q1,Q2),axis=0)

In [33]:
# Q

In [34]:
Q=matrix(2*Q,tc='d')
# Q

In [35]:
q=matrix(np.zeros((A.size[1],1)),tc='d')
# q

In [36]:
sol=solvers.qp(Q,q,A,b)

     pcost       dcost       gap    pres   dres
 0:  6.5331e-01  1.8617e+01  1e+02  2e+00  1e+02
 1:  4.1640e+00 -1.4621e+01  3e+01  5e-01  3e+01
 2:  5.4075e+00  2.5870e+00  3e+00  1e-02  5e-01
 3:  4.4849e+00  4.0273e+00  5e-01  1e-03  6e-02
 4:  4.3851e+00  4.3407e+00  4e-02  5e-16  9e-15
 5:  4.3765e+00  4.3740e+00  2e-03  6e-16  6e-15
 6:  4.3761e+00  4.3760e+00  1e-04  6e-16  3e-14
 7:  4.3761e+00  4.3761e+00  1e-05  5e-16  7e-14
 8:  4.3761e+00  4.3761e+00  2e-06  5e-16  4e-15
Optimal solution found.


In [37]:
sol['x']

<14x1 matrix, tc='d'>

In [38]:
ans = np.dot(np.transpose(sol['x']), np.transpose(Xtest_temp))

In [39]:
ans

array([[-2.07692336,  0.96581196,  3.18803421, -2.07692404, -0.86324787,
        -1.30769257,  2.96581196,  2.29914529, -1.15384634,  1.85470084]])